version: '3.8'

services:
    db:
      image: postgres:15-alpine
      container_name: todo_db
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: todo_db
      volumes:
        -   postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"

    app:
      env_file:
        - .env
      build: .
      container_name: todo_app
      ports:
        - "8080:8080"           # Открывает "окно" в контейнер
      restart: always
      depends_on:
        - db
      environment:
        - DB_URL=postgres://postgres:password@db:5432/todo_db

volumes:
  postgres_data: