version: '3.8'

services:
    db:
      image: postgres:15-alpine
      container_name: todo_db
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
        POSTGRES_DB: todo_db
      volumes:
        - ./migrations/001_create_tasks.up.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "5432:5432"

    app:
      build: .
      container_name: todo_app
      ports:
        - "8080:8080"           # Открывает "окно" в контейнер
      restart: on-failure
      depends_on:
        - db
      environment:
        - DATABASE_URL=postgres://postgres:password@db:5432/todo_db